#!/usr/bin/env python3
"""Generate the built-in scale table in dsp/Scale.h.

The tempered scales are computed from their definitions -- which fifths are
narrowed, and by how much -- rather than copied from a published table of
cents.  That way the numbers can be checked against the reasoning instead of
against someone else's typing, and the derivation is the documentation.

    python3 tools/scales.py > /tmp/builtins.inc
"""

from math import log2

def cents(ratio):
    return 1200 * log2(ratio)

PYTHAGOREAN_COMMA = cents(3 ** 12 / 2 ** 19)   # 23.460
SYNTONIC_COMMA    = cents(81 / 80)             # 21.506
SCHISMA           = cents(32805 / 32768)       #  1.954
PURE_FIFTH        = cents(3 / 2)

NAMES = ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "G#", "A", "Bb", "B"]


def from_fifths(tempered):
    """A 12-note scale from the chain Eb-G#, with named fifths narrowed.

    `tempered` maps a fifth, as a pair of note names, to the cents it is
    narrowed by.  Every fifth not named is pure.
    """
    chain = ["Eb", "Bb", "F", "C", "G", "D", "A", "E", "B", "F#", "C#", "G#"]
    pitch = {"C": 0.0}
    home = chain.index("C")
    for k in range(home, len(chain) - 1):
        a, b = chain[k], chain[k + 1]
        pitch[b] = pitch[a] + PURE_FIFTH - tempered.get((a, b), 0.0)
    for k in range(home, 0, -1):
        a, b = chain[k - 1], chain[k]
        pitch[a] = pitch[b] - PURE_FIFTH + tempered.get((a, b), 0.0)
    return [round(pitch[n] % 1200, 3) for n in NAMES[1:]] + [1200.0]


def equal(steps, period=2):
    return [round(cents(period) * k / steps, 3) for k in range(1, steps + 1)]


def narrow(fifths, amount):
    return {f: amount for f in fifths}


SCALES = [
    ("Pythagorean",
     "3-limit, the chain of pure fifths from Eb to G#",
     ["256/243", "9/8", "32/27", "81/64", "4/3", "729/512", "3/2",
      "128/81", "27/16", "16/9", "243/128", "2/1"]),

    ("Just Intonation (5-limit)",
     "Pure thirds and fifths in the home key, and audibly wrong away from it",
     ["16/15", "9/8", "6/5", "5/4", "4/3", "45/32", "3/2",
      "8/5", "5/3", "9/5", "15/8", "2/1"]),

    ("Quarter-comma Meantone",
     "Every fifth narrowed a quarter of a syntonic comma: pure major thirds",
     from_fifths(narrow(
         [("Eb", "Bb"), ("Bb", "F"), ("F", "C"), ("C", "G"), ("G", "D"),
          ("D", "A"), ("A", "E"), ("E", "B"), ("B", "F#"), ("F#", "C#"),
          ("C#", "G#")], SYNTONIC_COMMA / 4))),

    ("Werckmeister III",
     "1691. Four fifths narrowed by a quarter Pythagorean comma; all keys playable",
     from_fifths(narrow(
         [("C", "G"), ("G", "D"), ("D", "A"), ("B", "F#")],
         PYTHAGOREAN_COMMA / 4))),

    ("Kirnberger III",
     "Four fifths narrowed by a quarter syntonic comma, one by the schisma",
     from_fifths({**narrow([("C", "G"), ("G", "D"), ("D", "A"), ("A", "E")],
                           SYNTONIC_COMMA / 4),
                  **narrow([("F#", "C#")], SCHISMA)})),

    ("Vallotti",
     "Six fifths narrowed by a sixth of a Pythagorean comma; the rest pure",
     from_fifths(narrow(
         [("F", "C"), ("C", "G"), ("G", "D"), ("D", "A"), ("A", "E"),
          ("E", "B")], PYTHAGOREAN_COMMA / 6))),

    ("Young (1799)",
     "Vallotti's shape, rotated a fifth",
     from_fifths(narrow(
         [("C", "G"), ("G", "D"), ("D", "A"), ("A", "E"), ("E", "B"),
          ("B", "F#")], PYTHAGOREAN_COMMA / 6))),

    ("19-tone Equal",
     "Nineteen equal steps: meantone-like, with distinct sharps and flats",
     equal(19)),
    ("22-tone Equal", "Twenty-two equal steps", equal(22)),
    ("31-tone Equal",
     "Thirty-one equal steps, very close to quarter-comma meantone", equal(31)),
    ("53-tone Equal",
     "Fifty-three equal steps: fifths and thirds both near-pure", equal(53)),

    ("Bohlen-Pierce",
     "Thirteen equal divisions of 3/1, so it has no octave at all",
     equal(13, 3)),

    ("Harmonic Series 8-16",
     "The eighth to sixteenth harmonics, as a scale",
     [f"{k}/8" for k in range(9, 17)]),

    ("Slendro (5-tone equal)",
     "An equal-step approximation of the Javanese tuning, not a measurement of one",
     equal(5)),
]


def main():
    print("// GENERATED by tools/scales.py, and re-derivable from it.  The")
    print("// tempered scales are computed from their definitions -- which fifths")
    print("// are narrowed and by how much -- not copied from a table of cents.")
    print("inline const std::vector<BuiltInScale>& builtInScales()")
    print("{")
    print("    static const std::vector<BuiltInScale> t = {")
    for name, desc, values in SCALES:
        rows = [desc, str(len(values))]
        rows += [v if isinstance(v, str) else f"{v:.3f}" for v in values]
        print(f'        {{ "{name}",')
        print('          "' + "\\n".join(rows) + '\\n" },')
    print("    };")
    print("    return t;")
    print("}")


if __name__ == "__main__":
    main()
